# Generated by Django 5.1.3 on 2024-12-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ADMITTED', 'Admitted'), ('EMERGENCY', 'Emergency'), ('DISCHARGED', 'Discharged'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
