# Generated by Django 5.1.3 on 2025-01-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(default='hospital@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(default='Not Available', max_length=20),
        ),
    ]
