# Generated by Django 5.1.3 on 2025-01-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('0900', '9:00 AM'), ('1000', '10:00 AM'), ('1100', '11:00 AM'), ('1400', '2:00 PM'), ('1500', '3:00 PM'), ('1600', '4:00 PM')], max_length=4)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient')),
            ],
            options={
                'unique_together': {('department', 'appointment_date', 'time_slot')},
            },
        ),
    ]
