# Generated by Django 5.1.3 on 2024-12-08 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField()),
                ('admission_type', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('PLANNED', 'Planned'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred')], default='ADMITTED', max_length=20)),
                ('ward', models.CharField(blank=True, max_length=50, null=True)),
                ('bed_number', models.CharField(blank=True, max_length=10, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True, null=True)),
                ('discharge_diagnosis', models.TextField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attending_nurses', models.ManyToManyField(blank=True, limit_choices_to={'role': 'NURSE'}, related_name='nurse_admissions', to='authentication.staff')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admissions', to='authentication.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_admissions', to='authentication.patient')),
                ('primary_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_admissions', to='authentication.staff')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=15, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('prescription', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_records', to='authentication.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='authentication.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
