# Generated by Django 5.1.3 on 2024-12-27 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_patient_status'),
        ('patient_management', '0002_analyticsdata_appointment_labresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='medicalrecord',
            name='patient_man_date_2349dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicalrecord',
            name='patient_man_patient_d67b0d_idx',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='date',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='update_notes',
            field=models.TextField(blank=True, help_text='Notes about why this record was updated'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_medical_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_records', to='authentication.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_records', to='authentication.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='authentication.patient'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['-created_at'], name='patient_man_created_3e0500_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', '-created_at'], name='patient_man_patient_280fa3_idx'),
        ),
    ]
